# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/macaddr/all/macaddr.rbi
#
# macaddr-1.7.2

module Mac
  def self.addr; end
  def self.address; end
  def self.dependencies; end
  def self.description; end
  def self.from_getifaddrs; end
  def self.mac_address; end
  def self.mac_address=(arg0); end
  def self.parse(output); end
  def self.version; end
end
