# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `systemu` gem.
# Please instead update this file by running `bin/tapioca gem systemu`.


# source://systemu//lib/systemu.rb#9
class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin

  # source://systemu//lib/systemu.rb#10
  def systemu(*a, &b); end
end

# source://systemu//lib/systemu.rb#328
SystemU = SystemUniversal

# source://systemu//lib/systemu.rb#13
class SystemUniversal
  # instance methods
  #
  # @return [SystemUniversal] a new instance of SystemUniversal
  #
  # source://systemu//lib/systemu.rb#57
  def initialize(argv, opts = T.unsafe(nil), &block); end

  # source://systemu//lib/systemu.rb#181
  def child_program(config); end

  # source://systemu//lib/systemu.rb#143
  def child_setup(tmp); end

  # source://systemu//lib/systemu.rb#265
  def getopts(opts = T.unsafe(nil)); end

  # source://systemu//lib/systemu.rb#132
  def new_thread(child_pid, block); end

  # source://systemu//lib/systemu.rb#173
  def quietly; end

  # source://systemu//lib/systemu.rb#128
  def quote(*args, &block); end

  # source://systemu//lib/systemu.rb#215
  def relay(srcdst); end

  # source://systemu//lib/systemu.rb#228
  def slug_for(*args); end

  # source://systemu//lib/systemu.rb#75
  def systemu; end

  # source://systemu//lib/systemu.rb#238
  def tmpdir(d = T.unsafe(nil), max = T.unsafe(nil), &b); end

  # source://systemu//lib/systemu.rb#19
  def version; end

  class << self
    # source://systemu//lib/systemu.rb#20
    def description; end

    # source://systemu//lib/systemu.rb#46
    def host; end

    # source://systemu//lib/systemu.rb#46
    def host=(_arg0); end

    # source://systemu//lib/systemu.rb#46
    def pid; end

    # source://systemu//lib/systemu.rb#46
    def pid=(_arg0); end

    # source://systemu//lib/systemu.rb#46
    def ppid; end

    # source://systemu//lib/systemu.rb#46
    def ppid=(_arg0); end

    # source://systemu//lib/systemu.rb#48
    def quote(*words); end

    # source://systemu//lib/systemu.rb#33
    def ruby; end

    # source://systemu//lib/systemu.rb#46
    def turd; end

    # source://systemu//lib/systemu.rb#46
    def turd=(_arg0); end

    # source://systemu//lib/systemu.rb#18
    def version; end
  end
end

# source://systemu//lib/systemu.rb#17
SystemUniversal::VERSION = T.let(T.unsafe(nil), String)

# source://systemu//lib/systemu.rb#329
Systemu = SystemUniversal
