# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/uuid/all/uuid.rbi
#
# uuid-2.3.9

class UUID
  def generate(format = nil); end
  def iee_mac_address; end
  def initialize; end
  def inspect; end
  def mac_address; end
  def next_sequence; end
  def open_lock(mode); end
  def pseudo_mac_address; end
  def read_state(io); end
  def self.generate(format = nil); end
  def self.generator; end
  def self.mode; end
  def self.mode=(mode); end
  def self.server=(address); end
  def self.state_file(mode = nil); end
  def self.state_file=(path); end
  def self.validate(uuid); end
  def write_state(io); end
end
module UUID::Version
end
class UUID::Server
  def bind(address); end
  def initialize; end
  def listen(address); end
end
class UUID::Client
  def close; end
  def connect(address); end
  def generate(format = nil); end
  def initialize(address); end
  def inspect; end
  def next_sequence; end
end
